sudo: required
dist: trusty

language: node_js

node_js:
  - "8.4.0"

before_install:
  - rvm install 2.4.1

install:
  - npm install

script:
  - npm test

notifications:
  email:
    - matthew.dingee@opm.gov
