# Markdown config
highlighter: rouge
name: USAJOBS Help Center
description: Help with using USAJOBS, the one-stop shop for federal jobs.
exclude:
- Gemfile
- Gemfile.lock
- Gruntfile.js
- package.json
- README.md
- LICENSE.md
- CONTRIBUTING.md
- ".sass-cache"
- ".ruby-version"
- npm-debug.log
- node_modules
- js/vendor/future
keep_files: ['css', 'js']

# Setting a unique port number
port: 4001

baseurl: '/Help'
destination: ./_dist

permalink: pretty

author:
  name: USAJOBS
  url: https://help.usajobs.com/

repository:
  name: Help Center
  url: https://github.com/USAJOBS/Help/

produrl: 'https://www.usajobs.gov'

google_analytics_ua: UA-33523145-1

# plugins: ['jekyll-lunr-js-search', 'jekyll-sitemap', 'jekyll-redirect-from']
plugins:
  - jekyll-sitemap

lunr_search:
 min_length: 3
 excludes: [rss.xml]

how-to-cats: [Account, Application, Search, Misc]

collections:
  pages:
    output: true
    permalink: /:path/
